# Generated by Django 2.1.7 on 2019-05-15 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Time')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_code', models.CharField(max_length=10, unique=True, verbose_name='Department Code')),
                ('name', models.CharField(max_length=60, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('department', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Disabled')], verbose_name='Status')),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Time')),
                ('data', models.TextField(max_length=500, verbose_name='Content')),
                ('type', models.SmallIntegerField(choices=[(0, 'Video'), (1, 'Picture'), (2, 'Text')], verbose_name='Content Type')),
                ('department', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department'),
        ),
    ]
