# Generated by Django 2.1.7 on 2019-03-22 21:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Content Name')),
                ('status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Disabled')], verbose_name='Status')),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2019, 3, 23, 0, 49, 36, 758533), verbose_name='Creation Time')),
                ('data', models.TextField(max_length=500, verbose_name='Data')),
                ('type', models.SmallIntegerField(choices=[(0, 'Video'), (1, 'Pıcture'), (2, 'Text')], verbose_name='Data Type')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_code', models.CharField(max_length=10, unique=True, verbose_name='Department Code')),
                ('name', models.CharField(max_length=30, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department'),
        ),
    ]
