# Generated by Django 2.1.7 on 2019-03-22 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20190323_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='announcement',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 1, 16, 19, 93832), verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='content',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 1, 16, 19, 93832), verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 1, 16, 19, 93832), verbose_name='Date'),
        ),
    ]
