# Generated by Django 2.1.7 on 2019-05-02 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_auto_20190420_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 22, 22, 53, 432665), verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='content',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 22, 22, 53, 431614), verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='content',
            name='department',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 22, 22, 53, 432152), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department'),
        ),
    ]
