# Generated by Django 2.1.7 on 2019-05-03 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0014_auto_20190502_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Disabled')], verbose_name='Status')),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2019, 5, 3, 16, 44, 2, 764617), verbose_name='Creation Time')),
                ('data', models.TextField(max_length=500, verbose_name='Data')),
                ('type', models.SmallIntegerField(choices=[(0, 'Video'), (1, 'Picture'), (2, 'Text')], verbose_name='Data Type')),
                ('department', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='department',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 16, 44, 2, 766616), verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 16, 44, 2, 764617), verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
