# Generated by Django 2.1.7 on 2019-05-15 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Exam Date')),
                ('duration', models.CharField(max_length=10, verbose_name='Duration')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('title', models.CharField(max_length=60, verbose_name='Lecture Name')),
                ('lecturer', models.CharField(max_length=60, verbose_name='Lecturer Name')),
                ('department', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
            },
        ),
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Session Date')),
                ('duration', models.CharField(max_length=10, verbose_name='Duration')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Lecture')),
            ],
            options={
                'verbose_name': 'Lecture Session',
                'verbose_name_plural': 'Lecture Sessions',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Lecture'),
        ),
    ]
