# Generated by Django 2.1.7 on 2019-03-20 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 21, 50, 34, 37837)),
        ),
    ]
