# Generated by Django 2.1.7 on 2019-03-20 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 21, 53, 10, 300140)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_year',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 21, 53, 10, 299132)),
        ),
    ]
