# Generated by Django 2.1.7 on 2019-03-20 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20190320_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Lecture', 'verbose_name_plural': 'Lectures'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_year',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 22, 4, 44, 680352), verbose_name='Lecture Date '),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecturer',
            field=models.CharField(max_length=30, verbose_name='Lecturer Name'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Lecture Name'),
        ),
    ]
