# Generated by Django 2.1.7 on 2019-03-20 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20190320_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='l_year',
        ),
        migrations.AddField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 22, 18, 56, 881844)),
        ),
        migrations.AddField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 22, 18, 56, 881844), verbose_name='Lecture Date '),
        ),
    ]
