# Generated by Django 2.1.7 on 2019-03-20 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20190320_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.CharField(max_length=10, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 0, 24, 34, 987731), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 0, 24, 34, 987731), verbose_name='Lecture Date '),
        ),
    ]
