# Generated by Django 2.1.7 on 2019-03-20 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20190321_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 0, 49, 59, 746110), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 0, 49, 59, 745113), verbose_name='Lecture Date '),
        ),
    ]
