# Generated by Django 2.1.7 on 2019-03-22 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20190323_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 1, 16, 19, 86885), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 1, 16, 19, 86885), verbose_name='Lecture Date '),
        ),
    ]
