# Generated by Django 2.1.7 on 2019-03-23 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_auto_20190323_2202'),
        ('classes', '0012_auto_20190323_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 22, 2, 1, 518622), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 22, 2, 1, 518287), verbose_name='Lecture Date '),
        ),
    ]
