# Generated by Django 2.1.7 on 2019-03-24 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_auto_20190323_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 20, 41, 9, 277207), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 20, 41, 9, 273204), verbose_name='Lecture Date '),
        ),
    ]
