# Generated by Django 2.1.7 on 2019-04-19 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_auto_20190325_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 23, 44, 16, 823304), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 23, 44, 16, 822880), verbose_name='Lecture Date '),
        ),
    ]
