# Generated by Django 2.1.7 on 2019-04-19 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_auto_20190419_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 23, 46, 23, 53137), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 23, 46, 23, 52717), verbose_name='Lecture Date '),
        ),
    ]
