# Generated by Django 2.1.7 on 2019-04-20 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_auto_20190420_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 23, 19, 33, 821668), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 23, 19, 33, 820671), verbose_name='Lecture Date '),
        ),
    ]
