# Generated by Django 2.1.7 on 2019-05-02 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_auto_20190420_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 22, 22, 53, 430262), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='department',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 22, 22, 53, 429705), verbose_name='Lecture Date '),
        ),
    ]
