# Generated by Django 2.1.7 on 2019-05-03 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_auto_20190502_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='e_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 16, 44, 2, 760617), verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='l_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 16, 44, 2, 760617), verbose_name='Lecture Date '),
        ),
    ]
