# Generated by Django 2.1.7 on 2019-05-11 20:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0027_auto_20190508_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Session Date')),
                ('duration', models.CharField(max_length=10, verbose_name='Duration')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Lecture Session',
                'verbose_name_plural': 'Lecture Sessions',
            },
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='l_date',
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Lecture'),
        ),
    ]
